# Generated by Django 2.1.3 on 2019-10-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movtra', '0002_auto_20181213_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workedascast',
            name='person',
        ),
        migrations.AddField(
            model_name='workedascast',
            name='personID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
