# Generated by Django 2.1.3 on 2019-10-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movtra', '0003_auto_20191013_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workedascrew',
            name='person',
        ),
        migrations.AddField(
            model_name='workedascrew',
            name='personID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
