# Generated by Django 2.1.3 on 2019-10-13 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movtra', '0004_auto_20191013_1549'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
