# Generated by Django 2.1.3 on 2019-10-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movtra', '0005_delete_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workedascrew',
            old_name='order',
            new_name='gender',
        ),
        migrations.RemoveField(
            model_name='workedascast',
            name='id',
        ),
        migrations.RemoveField(
            model_name='workedascrew',
            name='id',
        ),
        migrations.AddField(
            model_name='workedascast',
            name='cast_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workedascast',
            name='credit_id',
            field=models.CharField(default='sadsada2', max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workedascast',
            name='gender',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workedascast',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workedascast',
            name='profile_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workedascrew',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workedascrew',
            name='profile_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workedascast',
            name='personID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='workedascrew',
            name='credit_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workedascrew',
            name='personID',
            field=models.IntegerField(),
        ),
    ]
