# Generated by Django 2.1.3 on 2019-10-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movtra', '0006_auto_20191027_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='workedascast',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workedascrew',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workedascast',
            name='credit_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workedascrew',
            name='credit_id',
            field=models.CharField(max_length=100),
        ),
    ]
