# Generated by Django 2.1.3 on 2019-10-31 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movtra', '0008_auto_20191027_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workedascrew',
            old_name='personID',
            new_name='person_id',
        ),
        migrations.RemoveField(
            model_name='workedascast',
            name='personID',
        ),
        migrations.AddField(
            model_name='workedascast',
            name='person_id',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
